version: '3.8'

services:
  api:
    image: mauricioarauujo1/news-recommender-api:latest
    platform: linux/amd64
    container_name: news-recommender-api
    ports:
      - "8000:8000"
    environment:
      - ENV=${ENV:-prod}
      - PYTHONPATH=/app
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-1
    restart: unless-stopped
